### ISSUE TITLE
3. User Portal Production

### ISSUE THREAD

**Issue by Fwedwickk** [Legacy-Banking/Bank-Simulator#39]
### **User Portal Production**

**Note:**  
This task involves developing the various sections within the user portal. Each section should be developed, reviewed, and tested individually to ensure the overall functionality of the user portal.

---

#### **Sub-Tasks:**

- **Dashboard (Account List):**
  - [ ] Bank Data Section (e.g., Savings account, Transaction account)
  - [ ] Download PDF, View Statements
  - [ ] Account Settings
  - [ ] Log Out

- **Transfer Funds:**
  - [ ] Transfer Funds Form
  - [ ] Logics & Safety

- **Pay Anyone:**
  - [ ] Pay Anyone Form
  - [ ] Logics & Safety

- **BPAY:**
  - [ ] BPAY Form
  - [ ] Logics & Safety

- **Bills & Upcoming Payments:**
  - [ ] Bills Page
  - [ ] Recurring Payments
  - [ ] Download PDF

---

### **Important:**
❗ **Please make sure to update the checklist from `[ ]` to `[x]` once a sub-task is completed to avoid confusion.**
