### ISSUE TITLE
4. Admin Portal Production

### ISSUE THREAD

**Issue by Fwedwickk** [Legacy-Banking/Bank-Simulator#53]
### **4. Admin Portal Production**

**Note:**  
This task involves developing the various sections within the admin portal. Each section should be developed, reviewed, and tested individually to ensure the overall functionality of the admin portal.

---

#### **Sub-Tasks:**

- **4.1 Dashboard (Client List):**
  - [ ] Client Data Section (e.g., How many people visit, Client stats)
  - [ ] Account Settings
  - [ ] Log Out

- **4.2 Manage Accounts:**
  - [ ] Client Account List
  - [ ] CRUD (Create, Read, Update, Delete)

- **4.3 Manage Default Transactions:**
  - [ ] Savings Account Page
  - [ ] Transactions Account Page

---

### **Important:**
❗ **Please make sure to update the checklist from `[ ]` to `[x]` once a sub-task is completed to avoid confusion.**
